import { motion } from "framer-motion";

/**
 * Live SVG badge preview that updates as the user types their name.
 * Mirrors the on-chain SVG generated by the smart contract.
 */
export default function BadgePreview({ name, tokenId = "?" }) {
  const displayName = name?.trim() || "Your Name";

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
      className="relative group"
    >
      {/* Glow effect behind the card */}
      <div className="absolute -inset-4 bg-gradient-to-br from-cyan-400/20 to-purple-400/20 rounded-3xl blur-2xl opacity-50 group-hover:opacity-70 transition-opacity duration-700" />

      {/* Badge SVG */}
      <motion.div
        animate={{ y: [0, -8, 0] }}
        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
        className="relative"
      >
        <svg
          width="320"
          height="320"
          viewBox="0 0 400 400"
          className="rounded-3xl drop-shadow-2xl"
        >
          {/* Background */}
          <defs>
            <linearGradient id="prevBg" x1="0%" y1="0%" x2="100%" y2="100%">
              <stop offset="0%" stopColor="#0a0a1a" />
              <stop offset="100%" stopColor="#1a0a2e" />
            </linearGradient>
            <linearGradient id="prevAccent" x1="0%" y1="0%" x2="100%" y2="0%">
              <stop offset="0%" stopColor="#00d4ff" />
              <stop offset="100%" stopColor="#7b61ff" />
            </linearGradient>
          </defs>

          <rect width="400" height="400" rx="24" fill="url(#prevBg)" />
          <rect
            x="16"
            y="16"
            width="368"
            height="368"
            rx="18"
            fill="none"
            stroke="url(#prevAccent)"
            strokeWidth="2"
            opacity="0.4"
          />

          {/* Decorative circle */}
          <circle cx="200" cy="70" r="6" fill="#00d4ff" opacity="0.6">
            <animate
              attributeName="opacity"
              values="0.3;0.8;0.3"
              dur="3s"
              repeatCount="indefinite"
            />
          </circle>

          {/* Title */}
          <text
            x="200"
            y="130"
            textAnchor="middle"
            fill="url(#prevAccent)"
            fontSize="26"
            fontWeight="bold"
            fontFamily="Arial, sans-serif"
          >
            EVENT BADGE
          </text>

          {/* Divider line */}
          <line
            x1="120"
            y1="155"
            x2="280"
            y2="155"
            stroke="url(#prevAccent)"
            strokeWidth="1.5"
            opacity="0.3"
          />

          {/* Name */}
          <text
            x="200"
            y="215"
            textAnchor="middle"
            fill="#ffffff"
            fontSize="24"
            fontFamily="Arial, sans-serif"
          >
            {displayName.length > 20
              ? displayName.slice(0, 18) + "..."
              : displayName}
          </text>

          {/* Token ID */}
          <text
            x="200"
            y="275"
            textAnchor="middle"
            fill="#00d4ff"
            fontSize="18"
            fontFamily="Arial, sans-serif"
          >
            #{tokenId}
          </text>

          {/* Footer */}
          <text
            x="200"
            y="355"
            textAnchor="middle"
            fill="#555555"
            fontSize="11"
            fontFamily="Arial, sans-serif"
          >
            Gasless Mint • Base Sepolia • UGF
          </text>
        </svg>

        {/* "LIVE PREVIEW" chip */}
        <div className="absolute -top-3 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full text-[10px] font-semibold tracking-wider uppercase glass border border-cyan-400/30 text-cyan-400">
          Live Preview
        </div>
      </motion.div>
    </motion.div>
  );
}
